require=function(r,e,n){function t(n,o){function i(r){return t(i.resolve(r))}function f(e){return r[n][1][e]||e}if(!e[n]){if(!r[n]){var c="function"==typeof require&&require;if(!o&&c)return c(n,!0);if(u)return u(n,!0);var l=new Error("Cannot find module '"+n+"'");throw l.code="MODULE_NOT_FOUND",l}i.resolve=f;var a=e[n]=new t.Module;r[n][0].call(a.exports,i,a,a.exports)}return e[n].exports}function o(){this.bundle=t,this.exports={}}var u="function"==typeof require&&require;t.Module=o,t.modules=r,t.cache=e,t.parent=u;for(var i=0;i<n.length;i++)t(n[i]);return t}({3:[function(require,module,exports) {
module.exports=function(t){window.addEventListener("load",function(){var o,n=navigator.userAgent,a="",e="",d="",i=0,r=0,c=0,s=0,m=0,p=0,S=0,l=0,v=0,E=0,g=0,u="Unknown",w=n.match(/(ipod).*\s([\d_]+)/i),L=n.match(/(ipad).*\s([\d_]+)/i),k=n.match(/(iphone)\sos\s([\d_]+)/i),h=n.match(/(android)\s([\d\.]+)/i);h?u="Android "+h[2]:k?u="iPhone, iOS "+k[2].replace(/_/g,"."):L?u="iPad, iOS "+L[2].replace(/_/g,"."):w&&(u="iPod, iOS "+w[2].replace(/_/g,"."));var C=u,f=n.match(/MicroMessenger\/([\d\.]+)/i);u="Unknown",f&&f[1]&&(C+=", WeChat "+(u=f[1])),o=C,u="Unknown",C=u="https:"==location.protocol?"HTTPS":"http:"==location.protocol?"HTTP":location.protocol.replace(":",""),u="Unknown",(e=n.toLowerCase().match(/ nettype\/([^ ]+)/g))&&e[0]?(u=(e=e[0].split("/"))[1],e=C+=", "+u):a=C,setTimeout(function(){var u=window.performance||window.msPerformance||window.webkitPerformance;if(u&&u.timing){var w=u.timing;w.navigationStart&&(d=d),w.navigationStart&&w.domainLookupStart&&(i=w.domainLookupStart-w.navigationStart),w.domainLookupEnd&&w.domainLookupStart&&(r=w.domainLookupEnd-w.domainLookupStart),w.connectEnd&&w.connectStart&&(c=w.connectEnd-w.connectStart,w.connectEnd&&w.secureConnectionStart&&(s=w.connectEnd-w.secureConnectionStart)),w.responseStart&&w.requestStart&&(m=w.responseStart-w.requestStart),w.responseEnd&&w.responseStart&&(p=w.responseEnd-w.responseStart),w.domComplete&&w.domLoading&&(S=w.domComplete-w.domLoading,w.domContentLoadedEventStart&&w.domLoading&&(l=w.domContentLoadedEventStart-w.domLoading)),w.loadEventEnd&&w.loadEventStart&&(v=w.loadEventEnd-w.loadEventStart),w.navigationStart&&w.loadEventEnd&&(E=w.loadEventEnd-w.navigationStart,g=w.domComplete-w.navigationStart)}t({system:o,ua:n,protocol:a,network:e,navigationStart:d,navigation:i,dns:r,tcp:c,ssl:s,request:m,response:p,domComplete:S,domLoaded:l,loadEvent:v,total:E,dom:g})},0)})};
},{}],4:[function(require,module,exports) {
var e=function(e){var t=e.stack.replace(/\n/gi,"").split(/\bat\b/).slice(0,9).join("@").replace(/\?[^:]+/gi,""),n=e.toString();return t.indexOf(n)<0&&(t=n+"@"+t),t},t=function(e,t){return Object.prototype.toString.call(e)==="[object "+(t||"Object")+"]"};module.exports=function(n){window.addEventListener("error",function(e){var t=e.message,r=e.filename,o=e.lineno,i=e.colno;n({msg:t,filename:r,lineno:o,colno:i})}),window.onerror=function(n,r,o,i,a){var c=n;a&&a.stack&&(c=e(a)),document.querySelector("#text").innerHTML=c,t(c,"Event")&&(c+=c.type?"--"+c.type+"--"+(c.target?c.target.tagName+"::"+c.target.src:""):""),alert(n)}};
},{}],2:[function(require,module,exports) {
module.exports=function(e,n){e=e+"?data="+JSON.stringify(n),(new Image).src=e};
},{}],5:[function(require,module,exports) {
module.exports.info=function(){var o,t=navigator.userAgent,n="",e="",r=location.host,a=location.pathname,i=location.href.split(a)[1],c="Unknown",l=t.match(/(ipod).*\s([\d_]+)/i),p=t.match(/(ipad).*\s([\d_]+)/i),s=t.match(/(iphone)\sos\s([\d_]+)/i),d=t.match(/(android)\s([\d\.]+)/i);d?c="Android "+d[2]:s?c="iPhone, iOS "+s[2].replace(/_/g,"."):p?c="iPad, iOS "+p[2].replace(/_/g,"."):l&&(c="iPod, iOS "+l[2].replace(/_/g,"."));var h=c,m=t.match(/MicroMessenger\/([\d\.]+)/i);return c="Unknown",m&&m[1]&&(h+=", WeChat "+(c=m[1])),o=h,c="Unknown",h=c="https:"==location.protocol?"HTTPS":"http:"==location.protocol?"HTTP":location.protocol.replace(":",""),c="Unknown",(e=t.toLowerCase().match(/ nettype\/([^ ]+)/g))&&e[0]?e=h+=", "+(c=(e=e[0].split("/"))[1]):n=h,{system:o,ua:t,protocol:n,network:e,host:r,url:a,query:i}},module.exports.merge=function(o,t){var n={};for(var e in o)n[e]=o[e];for(var e in t)n[e]=t[e];return n};
},{}],1:[function(require,module,exports) {
var global = (1,eval)("this");
var r=(0,eval)("this"),e=function(r){if(r.SE_REPORT)return r.SE_REPORT;var e=require("./libs/time"),i=require("./libs/error"),o=require("./tools/send"),n=require("./tools/util"),u=n.info(),t=n.merge;return r.SE_REPORT=function(r){var n=r.infoUrl,l=r.errorUrl;n&&l&&(e(function(r){o(n,t(r,u))}),i(function(r){o(l,t(r,u))}))}}(window);"undefined"!=typeof module&&(module.exports=e);
},{"./libs/time":3,"./libs/error":4,"./tools/send":2,"./tools/util":5}]},{},[1])